title: Baseline
logo: /assets/img/baseline-wordmark.svg
description: >
  Baseline gives you clear information about which web platform features are
  ready to use in your projects today.
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
